### ISSUE TITLE
[Report] The LiClipseText (Eclipse plugin) may cause MyBatipse not work

### ISSUE THREAD

**Issue by fancige** [mybatis/mybatipse#70]
The neon version comes with this plugin by default,  which causes MyBatipse not work in my case.

**Comment by harawata** [comment]
I have never used that plugin, but if you open files with its own editor, you won't be able to use MyBatipse features because MyBatipse enhances Eclipse's default editors.
Try opening files with the default editor.

![image](https://cloud.githubusercontent.com/assets/149268/21567438/77381404-ceef-11e6-9cbd-88289e54bfe7.png)

**Comment by fancige** [comment]
I knew that, i report this just want to help someone(i think there may be many of them, because it is the default plugin of new version eclipse). Actually, it still doesn't work if you only change the xml editor,  and   i have to uninstall this plugin to avoid this problem.

**Comment by harawata** [comment]
> because it is the default plugin of new version eclipse

Which package did you download?
I am using the 'Eclipse IDE for Java EE Developers' package downloaded from the [official download page](https://www.eclipse.org/downloads/eclipse-packages/) and it does not contain LiClipseText plugin.

**Comment by fancige** [comment]
Strangely, i didn't find it also in the archive package, i don't know why it could be there, maybe i installed it by accident? Anyway, nothing more, thanks your reply.

**Comment by harawata** [comment]
No problem. Thank you for taking the time to report!
