### ISSUE TITLE
Select statement used in nested result but not declared in interface causes a warning

### ISSUE THREAD

**Issue by rsprinkle** [mybatis/mybatipse#72]
A select statement that does not have a matching method in the mapper interface generates a warning even when it is used as part of a nested select in a resultMap.   

I do not think the warning should be present if the statement is used within a mapper.

**Comment by harawata** [comment]
Hi,

The warning is not about whether the statement is used, but about if there is a matching Java method in the corresponding mapper interface (mainly to avoid simple mistakes like typos).
I believe the current behavior is reasonable because...
- It is validated only when there is a corresponding Java mapper interface.
- It is a warning not an error.

**Comment by kazuki43zoo** [comment]
@rsprinkle Could you confirm @harawata 's comment?

**Comment by harawata** [comment]
Assuming my comment was a satisfactory answer. :D
