### ISSUE TITLE
Mybatipse is installed but the plugin is not prompted

### ISSUE THREAD

**Issue by padishahG** [mybatis/mybatipse#92]
![image](https://user-images.githubusercontent.com/22125316/47988928-7bf93c00-e11e-11e8-8871-522cb990782e.png)
![image](https://user-images.githubusercontent.com/22125316/47988950-8c111b80-e11e-11e8-84d2-86c4c71076ea.png)
There are no prompts in the mapper file。thanks

**Comment by harawata** [comment]
Hi @padishahG ,

Have you tried re-opening the editor?
It seems that the plugin does not work if the editor is opened before installing the plugin.

**Comment by kenjdavidson** [comment]
During my debugging of this, I came across the same problem.  The XML Validator wasn't running when opening the file - both before and after installing the plugin.  After looking around a little I found the issue was that XML Validation was turned off:

Preferences > Validation - was enabled
Preferences > XML > XML Files > Validation - Enable markup validation was unchecked

By right clicking on the XML file an going to Validate (menu item) it worked properly.  After checking the option above (Enable markup validation) the XML validator was firing on each change as expected.  Not sure if this is your issue, but worth a shot since it took me a bit to find it.

**Comment by padishahG** [comment]
@harawata Thank you, suddenly it will be fine.

**Comment by padishahG** [comment]
@kenjdavidson Thank you very much, have written so much. Hard work. Just restart a few times and it will be fine. Haha

**Comment by harawata** [comment]
Assuming this is not an issue. :)
